namespace CEIT.Player
{
	public enum PlayerIntents
	{
		NONE,
		PRIMARY,
		SECONDARY,
		CHANGE_INTERACTION_UP,
		CHANGE_INTERACTION_DOWN,
		CHANGE_INTERACTION_VALUE_UP,
		CHANGE_INTERACTION_VALUE_DOWN,
		PAUSE_MENU,
		TABBED_MENU,
		INTERACTIONS_WHEEL,
		SHOW_INFO
	}
}